### ISSUE TITLE
Just a thank you

### ISSUE THREAD

**Issue by Mast3rMind** [Jeiwan/blockchain_go#1]
I was looking for something like this for a while, thanks for taking the time to create this useful resource to learn more about what makes the blockchain work.
Accept BTC tips?
Cheers

**Comment by Jeiwan** [comment]
@Mast3rMind Thank you! I'm really happy this series of posts if useful for people. I believe, for programmers and developers, the blockchain technology will be as crucial to know as the HTTP protocol for a modern web-developer.
My BTC wallet for tips: 18ks2hwABQ56n5syejorKvU3ChiVCLMKNT

**Comment by Mast3rMind** [comment]
@Jeiwan Sent a few bits your way!

**Comment by Jeiwan** [comment]
@Mast3rMind Awesome! Thank you!
