### ISSUE TITLE
./main.go:4:9: undefined: CLI

### ISSUE THREAD

**Issue by nhatlee** [Jeiwan/blockchain_go#10]
Dear Jeiwan,
I try to build your code with `GoLand` IDE (Go `1.9.2`) and got the error 
`# command-line-arguments
./main.go:4:9: undefined: CLI

Process finished with exit code 2`
How to fix it?

**Comment by outprog** [comment]
@nhatlee 你构建的是master还是某个part？

**Comment by nhatlee** [comment]
@outprog English please.

**Comment by outprog** [comment]
@nhatlee Sorry, look the pic...
Which branch you build, master or others?

**Comment by nhatlee** [comment]
I build on master branch.

**Comment by outprog** [comment]
@nhatlee master branch is working good. I think you just build main.go, this is not error in code.

**Comment by Jeiwan** [comment]
Yes, something is wrong with the IDE, `CLI` is defined in `cli.go`.

**Comment by Jeiwan** [comment]
@snackyoung Something is wrong with the way you run the code. The error says that `CLI` wasn't found but it's there: https://github.com/Jeiwan/blockchain_go/blob/master/cli.go You need to pass all the files to the go compiler or open the whole directory in your IDE.

**Comment by UsrAlpha** [comment]
You only need to change the goland run/debug configurations->Run Kind Package

**Comment by UsrAlpha** [comment]
You only need to change the goland run/debug configurations->Run Kind Package
