### ISSUE TITLE
I'm getting that error when i run main.go

### ISSUE THREAD

**Issue by devf33** [Jeiwan/blockchain_go#14]
![image](https://user-images.githubusercontent.com/33232264/34561079-43eb48d6-f140-11e7-8024-96c32fea7faf.png)

**Comment by outprog** [comment]
https://github.com/Jeiwan/blockchain_go/issues/10

**Comment by Jeiwan** [comment]
This is not how you run Go programs. You need to pass all the .go files to `go run`, or you can use `go build` and run the executable after it's compiled.
