### ISSUE TITLE
Include Package Import Names in Write-Up

### ISSUE THREAD

**Issue by madranet** [Jeiwan/blockchain_go#15]
Thanks for the tutorial.  I'm working my way through it now. 

One suggestion though. Could you reference which new packages you're importing at each stage.  I'm following along with the tutorial and building bit-by-bit and I have to keep running the code, after each new section is introduced, waiting for the `undefined: XXX` errors and then looking up the Golang docs to find which package I need to import to include `XXX`

**Comment by Jeiwan** [comment]
The articles give general idea if how it works, it makes no sense putting all the code there – this is what Github for.
