### ISSUE TITLE
Unable to verify wallet address generated seconds before

### ISSUE THREAD

**Issue by joegalaxy71** [Jeiwan/blockchain_go#17]
Hi, I tryed go install in both macOs and Debian, same problem.

`./blockchain_go createblockchain -address 1PEiixXK7E8S7pqkjTiePUnP9jZFBonBR9
2018/01/25 18:08:00 ERROR: Address is not valid
panic: ERROR: Address is not valid

goroutine 1 [running]:
log.Panic(0xc420055dc8, 0x1, 0x1)
	/usr/local/go/src/log/log.go:326 +0xc0
main.(*CLI).createBlockchain(0xc420055f70, 0x7fff5fbffc2a, 0x22, 0xc420016048, 0x5)
	/Users/simo/go/src/blockchain_go/cli_createblockchain.go:10 +0x169
main.(*CLI).Run(0xc420055f70)
	/Users/simo/go/src/blockchain_go/cli.go:119 +0x615
main.main()
	/Users/simo/go/src/blockchain_go/main.go:5 +0x2b`

**Comment by beb59** [comment]
+1
same problem

**Comment by Jeiwan** [comment]
Thanks for reporting. It's fixed now.
