### ISSUE TITLE
Could I translate your articles to Chinese?

### ISSUE THREAD

**Issue by aQuaYi** [Jeiwan/blockchain_go#18]
Could I?

**Comment by liuchengxu** [comment]
@aQuaYi Hi, I have already finished translating the series to Chinese, see [part 1-7](https://github.com/liuchengxu/blockchain-tutorial/tree/master/content). 

@Jeiwan Hope you don't mind that I started the translating without your permission. 🙈

**Comment by Jeiwan** [comment]
@liuchengxu thanks for your work, I added links to your translations.
