### ISSUE TITLE
something in base58.go confused me 

### ISSUE THREAD

**Issue by angelinazf** [Jeiwan/blockchain_go#2]
```go
for b := range input {
       if b == 0x00 {
		result = append([]byte{b58Alphabet[0]}, result...)
	} else {
		break
	}
}
```
in this cycle, b is the index of input, not the value, so i think it may be wrong here.
it should be 
```go
for _, b := range input {
         ...
}
```
both in two functions this file(line26 & line42).

**Comment by angelinazf** [comment]
i realized

**Comment by Jeiwan** [comment]
@angelinazf You're right! Thank you! It's fixed now.
