### ISSUE TITLE
Loop w/o end point

### ISSUE THREAD

**Issue by filipevarjao** [Jeiwan/blockchain_go#20]
If you run the project in the part_2 there is no end, and keeps printing the hash forever.
> Mining the block containing "Genesis Block"
> 3f22aecfa055d42189abe136137514db35bd852762b9d1129fd8098bc0bc5c45

**Comment by filipevarjao** [comment]
Just need remove the negative signal, https://github.com/Jeiwan/blockchain_go/blob/part_2/proofofwork.go#L62

**Comment by Jeiwan** [comment]
It doesn't keep running forever, the difficulty is just too high. To lower it, change `24` to `16` here: https://github.com/Jeiwan/blockchain_go/blob/part_2/proofofwork.go#L15
