### ISSUE TITLE
Sometimes createwallet generates invalid address.

### ISSUE THREAD

**Issue by fe1t** [Jeiwan/blockchain_go#29]
Step to reproduce
1. Write some shell script that createwallet
2. Use that address to with createblockchain command with flag -address

loop until error occurs 'panic: ERROR: Address is not valid'
that wont take too long.

**Comment by pengzhaocheng16** [comment]
have you find the reason

**Comment by pengzhaocheng16** [comment]
Have you found out the reason

**Comment by fe1t** [comment]
I think it's about wrong implementation in base58 but I've not taken a closer look anymore
Cheers!
