### ISSUE TITLE
Differences in []byte to string converting?

### ISSUE THREAD

**Issue by bbortt** [Jeiwan/blockchain_go#67]
Hi there
Thanks for your great article. I just wanted to know the differences between `fmt.Sprintf("%s", []byte)` and `string([]byte[:])`? Are there any advantages in one way (you're using the first mostly)?
Many thanks!
Timon

**Comment by mubarizkyc** [comment]
fmt.Sprintf   can format byte slice in various ways by changing specifiers ,while string(byteSlice[:]) is fast direct conversion
