### ISSUE TITLE
wrong base58 implentation

### ISSUE THREAD

**Issue by Tanete** [Jeiwan/blockchain_go#7]
Hi. There should be something wrong with your base58 implentation after this [commit](https://github.com/Jeiwan/blockchain_go/commit/cb32e7ca13c3b1c61f78f6d2e1025d85acdee447). 

It will cause wallet address decode error like this.

 ./blockchain_go createblockchain -address 1DU9fP5ZtqjR3MJvHvV7vvWsuZcBFZ2PeG
2017/11/22 02:00:46 ERROR: Address is not valid
panic: ERROR: Address is not valid

**Comment by Jeiwan** [comment]
Sorry for not fixing this in time, and thanks for the PR. It's fixed now.
