### ISSUE TITLE
Any reason why you're using secp256r1 rather than secp256k1 ?

### ISSUE THREAD

**Issue by adityathebe** [Jeiwan/blockchain_go#75]
https://github.com/Jeiwan/blockchain_go/blob/fee9bfd3afeef02e237e93335fa2076c30b9d6d6/wallet.go#L78

**Comment by Jeiwan** [comment]
That was a mistake. There was a different issue I still haven't fixed it: https://github.com/Jeiwan/blockchain_go/issues/11

Sorry for the long delay!
